all: clean
	pdflatex presentation &&  pdflatex presentation 

clean: 
	rm -rf presentation.lot presentation.acn presentation.dvi presentation.glo presentation.glsdefs presentation.ist presentation.log presentation.pdf presentation.brf presentation.bbl presentation.blg presentation.out presentation.toc presentation.aux presentation.toc presentation.lof presentation.nav presentation.snm
